spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.67.239.216:3306/aquaculture?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Yuanyulou789!
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  thymeleaf:
    cache: false
    enabled: false
server:
  port: 8088